Skrevet om konfigurasjon og versjonskontroll
Freshairkaboom/Gruppe2Systemutvikling pull request #104
Opened 2024-04-11 11:46 UTC by btfman75

Har skrevet litt om konfigurasjon og versjonskontroll. Tar gjerne imot tips hvis det er noe jeg mangler

2024-04-11 16:54 UTC, Freshairkaboom requested changes

2024-04-11 16:54 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +I dette prosjektetteamet var vi tilsammen 7 stykker. Siden noen av medlemmene i teamet bor et stykke fra skolen ble vi enige om å ha de fleste møtene over nett. Vi ble enige om å bruke Discord fordi
```suggestion
I dette prosjektetteamet var vi tilsammen syv personer. Siden noen av medlemmene i teamet bor et stykke fra skolen ble vi enige om å ha de fleste møtene over nett. Vi ble enige om å bruke Discord fordi det er en enkel men effektiv kommunikasjonsplattform. Noen av medlemmene hadde ikke brukt Discord før, mens andre kjente godt til det. Discord er forholdsvis enkelt å lære seg, så vi kom raskt i gang med å bruke denne plattformen. Fordelen med Discord er at du kan lage stemme-kanaler der de som ønsker å arbeide sammen kan samles. Det er også mulighter for å dele skjerm så alle kan vise de andre hva de jobber med eller om de trenger hjelp fra andre i gruppen. Du kan "tagge" andre medlemmer eller hele gruppa hvis du ønsker raskt svar på et spørsmål. De får da et varsel om at noen ønsker å få tak i dem. 
```

2024-04-11 16:54 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +Github er en versjonskontroll som er mye bruk av utviklere. Den gir brukerne mulighet til å laste opp og endre dokumenter. Det er som en felles mappesystem der du kan bidra til andres dokumenter ved
```suggestion
Github er en versjonskontroll plattform som er mye brukt av utviklere. Den gir brukerne mulighet til å laste opp og endre dokumenter. Det er som et felles mappesystem der du kan bidra til andres dokumenter ved å endre en kopi av dokumentet i hovedmappa. Når vi jobbet i Github la vi ut arbeidet vårt i "Pull Requests" når vi var ferdig med det vi arbeidet med. Da kunne andre medlemmer av teamet gå inn å se hva vi hadde gjort, så kunne de kommentere arbeidet vårt, og komme med innspill til eventuelle endringer som burde bli gjort. 
```

2024-04-16 08:40 UTC, Adrijoh commented
Folkelig forklart. Mer enn bra nok for min del. Merge i vei!

2024-04-16 08:42 UTC, Adrijoh approved these changes

2024-04-16 08:46 UTC, Adrijoh approved these changes

2024-04-16 08:46 UTC, Adrijoh approved these changes

2024-04-16 08:47 UTC, Adrijoh approved these changes

2024-04-16 08:49 UTC, Freshairkaboom approved these changes

2024-04-16 08:49 UTC, merged