Work Breakdown Structure
Freshairkaboom/Gruppe2Systemutvikling pull request #111
Opened 2024-04-16 09:30 UTC by Ramona3401

2024-04-16 09:31 UTC, Freshairkaboom commented
Alt tekst?

2024-04-16 09:36 UTC, btfman75 approved these changes
Synes det ser bra ut

2024-04-16 09:43 UTC, Freshairkaboom requested changes
Alt tekst i rapporten trengs.

2024-04-18 09:15 UTC, Ramona3401 commented
Skal jeg legge det som PR ...Denne illustrasjonen presenterer arbeidsnedbrytningsstrukturen, WBS (Work Breakdown Structure), for vårt HytteApp-prosjekt. WBS er et verktøy som deler prosjektet ned i mindre og mer håndterbare deler...

2024-04-18 11:49 UTC, Freshairkaboom approved these changes

2024-04-18 11:49 UTC, merged