Laget USE case tabeller i word
Freshairkaboom/Gruppe2Systemutvikling pull request #72
Opened 2024-03-26 13:26 UTC by btfman75

2024-03-26 13:31 UTC, btfman75 commented
<img width="875" alt="Skjermbilde 2024-03-26 kl  13 49 59" src="https://github.com/Freshairkaboom/Gruppe2Systemutvikling/assets/143797039/903930cd-bd63-42b3-9001-6be19699fbef">

2024-03-26 13:33 UTC, btfman75 commented
![Skjermbilde 2024-03-26 kl  14 32 20](https://github.com/Freshairkaboom/Gruppe2Systemutvikling/assets/143797039/963eb5e9-153c-4795-9db8-fe289e6c8c44)

2024-03-26 13:34 UTC, btfman75 commented
![Skjermbilde 2024-03-26 kl  14 33 56](https://github.com/Freshairkaboom/Gruppe2Systemutvikling/assets/143797039/5769383d-0626-4a79-a634-644ee2d1587f)

2024-03-26 13:36 UTC, btfman75 commented
![Skjermbilde 2024-03-26 kl  14 36 07](https://github.com/Freshairkaboom/Gruppe2Systemutvikling/assets/143797039/9de74fb3-39fd-4321-ab1c-8451ce1e6873)

2024-03-26 13:36 UTC, btfman75 commented
![Skjermbilde 2024-03-26 kl  14 36 18](https://github.com/Freshairkaboom/Gruppe2Systemutvikling/assets/143797039/42edf5f1-9eab-46d4-8258-4c89ba9034cb)

2024-04-01 17:14 UTC, Freshairkaboom requested changes
Noen forslag til endring, vi kan ikke bruke så mye ekstra tid på det, så det går fint at du ikke har skrevet mer. :)

2024-04-01 17:14 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +
Her var det litt mange mellomrom ned til neste setning.

2024-04-01 17:14 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +Her skal det settes in UC diagram
Hvis det er et bilde, så bør det stå som en alt tekst/forklarende tekst for de som ikke får bildet opp eller ikke kan se bildet av forskjellige grunner, det er spesifikt bedt om av Ingrid.

Så for eksempel: Figur: UC-diagram

2024-04-01 17:14 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +Use Case beskrivelser
Trenger sikkert ikke skrive dette når du har det i undertittelen allerede

2024-04-01 17:14 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +Her skal det settes inn tabeller
Hvis det er flere tabeller, så kan hver tabell ha en egen tekst så det blir enklere å se akkurat hvor man skal putte de når man setter sammen det siste dokumentet.

For eksempel: Tabell: UC1

Hvis ikke kan det stå Tabell: UC1 til UC4.

2024-04-09 09:28 UTC, monicaazaria commented
Kjempe fin tabell!

2024-04-09 09:45 UTC, Adrijoh commented
Dette ser bra ut og det vil se enda bedre ut i et word-dokument!

2024-04-09 09:54 UTC, Freshairkaboom commented on Prosjektrapport-V2.md
> +Her skal det settes in UC diagram.
`Figur: Use case diagram.`

2024-04-09 10:08 UTC, ShaimaNazand98 commented
den ser veldig fin ut

2024-04-09 10:25 UTC, Freshairkaboom approved these changes

2024-04-09 10:27 UTC, merged